language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - export TZ='Asia/Hong_Kong'

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - gitbook build

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master
